# Global properties go here
spring:
   profiles:
      active: test
   datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
mvc:
   max-size-trace-payload: 50000
jms:
   listener-concurrency: 1-5
   agreement-queue: sandbox.agreement
client:
    fx-rate: http://api.fixer.io
---
# Test properties go here
spring:
   profiles: test
   datasource:
      username: sa
      password:
logging:
    level:
      org.galatea.starter.service.client.IFxRestClient: DEBUG
---
# Dev properties go here
spring:
   profiles: dev
   datasource:
      username: sa
      password:
logging:
    level:
      org.galatea.starter.service.client.IFxRestClient: DEBUG
---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:
