# Global properties go here
spring:
   datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
mvc:
   max-size-trace-payload: 50000
jms:
   listener-concurrency: 1-5
   agreement-queue: sandbox.agreement      

logging:
   level:
      # Feign logging only responds to the DEBUG level
      org.galatea.starter.service.client.IFXRestClient: DEBUG
---
# Test properties go here
spring:
   profiles: test
   datasource:
      username: sa
      password:
---
# Dev properties go here
spring:
   profiles: dev
   datasource:
      username: sa
      password:
---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:

